services:
  - type: web
    name: okx-limit-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OKX_API_KEY
        sync: false
      - key: OKX_API_SECRET
        sync: false
      - key: OKX_PASSPHRASE
        sync: false
      - key: WEBHOOK_SECRET
        sync: false